# Generated by Django 5.1 on 2024-10-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='score',
            name='performer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='performers',
        ),
        migrations.RemoveField(
            model_name='score',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.DeleteModel(
            name='Performer',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
